In [24]:
import cwrangle as cw
import pandas as pd
import geocoder
import numpy as np
import re
import importlib
importlib.reload(cw)

Read in USA 2017

In [25]:
usa2017 = pd.read_csv('d3data/usa2017.csv')

In [26]:
usa2017 = usa2017[(usa2017['p19_1l'] > 0) & (usa2017['p19_1l'] < 999999997)]
usa2017 = usa2017[(usa2017['p19_2l'] > 0) & (usa2017['p19_2l'] < 999999997)]
usa2017 = usa2017[(usa2017['p20l'] > 0) & (usa2017['p20l'] < 999999997)]
usa2017 = usa2017[(usa2017['p26'] > 0) & (usa2017['p26'] < 999999997)]
usa2017 = usa2017[(usa2017['p11_1d'] > 0) & (usa2017['p11_1d'] < 97)]
usa2017 = usa2017[(usa2017['p11_1m'] > 0) & (usa2017['p11_1m'] < 9997)]
usa2017 = usa2017[(usa2017['p14_1'] > 0) & (usa2017['p14_1'] < 9999997)]

In [27]:
usa2017.to_csv('d3data/cutusa.csv', encoding='latin1')

In [28]:
us2017 = cw.go('d3data/cutusa.csv', 'Values/ValoresUSA2017.csv', 'Variable', 'USA', 2017)

In [29]:
us2017.head()

,year,sex,age,read_write,head_house,home_dept,mex_port,trans_crossm,coyote_usd,trans_crossu,...,country,deported,first_citynew,second_citynew,long_citynew,us_entrynew,mex_port_lat,mex_port_long,us_entry_lat,us_entry_long
0,2017,Hombre,47,Sí,Sí,Choluteca,"Cuauhtémoc, Chiapas",Ninguno (caminando o nadando),No contrató persona o pollero para que le ayud...,Ninguno (caminando o nadando),...,El Salvador,USA,"Heróica Puebla de Zaragoza , Puebla","San Luis Potosí , San Luis Potosí","Monterrey , Nuevo León","Nuevo Laredo , Tamaulipas",15.665483,-92.003579,27.415460,-99.541843
1,2017,Hombre,19,Sí,No,Francisco Morazán,"Ciudad Hidalgo, Chiapas",Autobús o camioneta,2500,"Balsas (cámaras de llanta, tambos, maderos)",...,El Salvador,USA,"Reynosa , Tamaulipas","Tapachula de Córdova y Ordóñez , Chiapas","Reynosa , Tamaulipas","Reynosa , Tamaulipas",14.679726,-92.150326,25.836636,-98.370859
2,2017,Hombre,18,Sí,No,Francisco Morazán,"Cuauhtémoc, Chiapas",Autobús o camioneta,No contrató persona o pollero para que le ayud...,"Balsas (cámaras de llanta, tambos, maderos)",...,El Salvador,USA,"Heróica Puebla de Zaragoza , Puebla","Monterrey , Nuevo León","Heróica Puebla de Zaragoza , Puebla","Nuevo Laredo , Tamaulipas",15.665483,-92.003579,27.415460,-99.541843
3,2017,Hombre,19,El último año de escuela que aprobó es desde b...,No,Choluteca,"Ciudad Hidalgo, Chiapas",Autobús o camioneta,3000,"Balsas (cámaras de llanta, tambos, maderos)",...,El Salvador,USA,"Benito Juárez , Distrito Federal","Tapachula de Córdova y Ordóñez , Chiapas","Monterrey , Nuevo León","Reynosa , Tamaulipas",14.679726,-92.150326,25.836636,-98.370859
4,2017,Hombre,21,El último año de escuela que aprobó es desde b...,No,Copan,"Cuauhtémoc, Chiapas",Autobús o camioneta,No contrató persona o pollero para que le ayud...,"Balsas (cámaras de llanta, tambos, maderos)",...,El Salvador,USA,"Tapachula de Córdova y Ordóñez , Chiapas","Monterrey , Nuevo León","Reynosa , Tamaulipas","Reynosa , Tamaulipas",15.665483,-92.003579,25.836636,-98.370859

Read in Mexico 2017

In [232]:
mex2017 = pd.read_csv('d3data/mex2017.csv')

In [233]:
mex2017 = mex2017[(mex2017['p22_1l'] > 0) & (mex2017['p22_1l'] < 999999997)]
mex2017 = mex2017[(mex2017['p22_2l'] > 0) & (mex2017['p22_2l'] < 999999997)]
mex2017 = mex2017[(mex2017['p24l'] > 0) & (mex2017['p24l'] < 999999997)]
mex2017 = mex2017[(mex2017['p11_1d'] > 0) & (mex2017['p11_1d'] < 997)]
mex2017 = mex2017[(mex2017['p11_1m'] > 0) & (mex2017['p11_1m'] < 9997)]
mex2017 = mex2017[(mex2017['p15'] > 0) & (mex2017['p15'] < 9999997)]
mex2017 = mex2017[(mex2017['p34e'] > 0) & (mex2017['p34e'] < 97)]
mex2017 = mex2017[(mex2017['p34m'] > 0) & (mex2017['p34m'] < 99997)]

In [234]:
mex2017.to_csv('d3data/cutmex.csv', encoding='latin1')

In [235]:
mex2017 = cw.go('d3data/cutmex.csv', 'Values/ValoreMex2017.csv', 'Variable', 'Mex', 2017)

In [236]:
mex2017.head()

,year,sex,age,read_write,head_house,home_dept,mex_port,fellow_travs,trans_crossm,coyote_usd,country,deported,first_citynew,second_citynew,long_citynew,deported_place,mex_port_geom
0,2017,Hombre,22,Aprobó de básicos-secundaria en adelante,Sí,La Paz,"Ciudad Hidalgo, Chiapas",En este viaje iba solo(a),Autobús o camioneta,En este viaje no contrató alguna persona que l...,El Salvador,Mexico,"Arriaga , Chiapas","Veracruz , Veracruz de Ignacio de la Llave","Arriaga , Chiapas","Piedras Negras, Coahuila de Zaragoza","[14.679726, -92.150326]"
1,2017,Hombre,36,Aprobó de básicos-secundaria en adelante,Sí,Cortés,"Ciudad Hidalgo, Chiapas",2,Autobús o camioneta,7000,El Salvador,Mexico,"Villahermosa , Tabasco","Arriaga , Chiapas","Veracruz , Veracruz de Ignacio de la Llave","Piedras Negras, Coahuila de Zaragoza","[14.679726, -92.150326]"
2,2017,Hombre,32,Aprobó de básicos-secundaria en adelante,Sí,Choluteca,"Cuauhtémoc, Chiapas",En este viaje iba solo(a),Autobús o camioneta,En este viaje no contrató alguna persona que l...,El Salvador,Mexico,"San Luis Potosí , San Luis Potosí","Tapanalá , Oaxaca","Tuxtla Gutiérrez , Chiapas","San Pedro Tapanatepec, Oaxaca","[15.665483, -92.003579]"
3,2017,Hombre,33,Aprobó de básicos-secundaria en adelante,Sí,Choluteca,"Ciudad Hidalgo, Chiapas",En este viaje iba solo(a),Autobús o camioneta,En este viaje no contrató alguna persona que l...,El Salvador,Mexico,"Ciudad Hidalgo , Chiapas","Ciudad Ixtepec , Oaxaca","Arriaga , Chiapas","Matías Romero, Oaxaca","[14.679726, -92.150326]"
4,2017,Hombre,29,Aprobó de básicos-secundaria en adelante,No,Comayagua,"Ciudad Hidalgo, Chiapas",En este viaje iba solo(a),Autobús o camioneta,En este viaje no contrató alguna persona que l...,El Salvador,Mexico,"Tapachula de Córdova y Ordóñez , Chiapas","Tapachula de Córdova y Ordóñez , Chiapas","Ciudad Ixtepec , Oaxaca","Veracruz, Veracruz de Ignacio de la Llave","[14.679726, -92.150326]"

In [237]:
mex2017.to_csv('d3data/encodedmex.csv', encoding='latin1')
us2017.to_csv('d3data/encodedusa.csv', encoding='latin1')